/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;

/**
 *
 * @author vivia
 */
public class AddNewProcess extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProcess
     */
    public AddNewProcess() {
        initComponents();
        this.setSize(432, 460);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setLayout(new BorderLayout(10,10));
        this.setTitle("Crear Proceso");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new GUI.PanelRound();
        cyclestoexception3 = new javax.swing.JSpinner();
        exceptionservicecycles2 = new javax.swing.JSpinner();
        memorynedded2 = new javax.swing.JSpinner();
        instructions1 = new javax.swing.JSpinner();
        priority1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cyclestoexception2 = new javax.swing.JSpinner();
        memorynedded1 = new javax.swing.JSpinner();
        exceptionservicecycles1 = new javax.swing.JSpinner();
        instructions = new javax.swing.JSpinner();
        priority = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        iscpubound = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(432, 445));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cyclestoexception3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        panelRound1.add(cyclestoexception3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 150, 30));

        exceptionservicecycles2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        panelRound1.add(exceptionservicecycles2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 150, 30));

        memorynedded2.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        panelRound1.add(memorynedded2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 150, 30));

        instructions1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        panelRound1.add(instructions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 150, 30));

        priority1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        panelRound1.add(priority1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 150, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Nro. Instrucciones");
        panelRound1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelRound1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Cantidad de memoria ");
        panelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 30));
        panelRound1.add(cyclestoexception2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 150, 30));
        panelRound1.add(memorynedded1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 150, 30));
        panelRound1.add(exceptionservicecycles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 150, 30));
        panelRound1.add(instructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 150, 30));
        panelRound1.add(priority, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 150, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelRound1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Cantidad de memoria ");
        panelRound1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nro. Instrucciones");
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Nro de ciclos para satisfacer");
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("excepción");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nro de ciclos hasta la  ");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Es consumidor de CPU?");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Prioridad");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("la excepción");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Proceso");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        panelRound1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 150, 30));

        iscpubound.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));
        iscpubound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iscpuboundActionPerformed(evt);
            }
        });
        panelRound1.add(iscpubound, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 150, 30));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 440, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iscpuboundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iscpuboundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iscpuboundActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cyclestoexception2;
    private javax.swing.JSpinner cyclestoexception3;
    private javax.swing.JSpinner exceptionservicecycles1;
    private javax.swing.JSpinner exceptionservicecycles2;
    private javax.swing.JSpinner instructions;
    private javax.swing.JSpinner instructions1;
    private javax.swing.JComboBox<String> iscpubound;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner memorynedded1;
    private javax.swing.JSpinner memorynedded2;
    private javax.swing.JTextField name1;
    private GUI.PanelRound panelRound1;
    private javax.swing.JSpinner priority;
    private javax.swing.JSpinner priority1;
    // End of variables declaration//GEN-END:variables
}
